name: GITHUB-DEMO-WORKFLOW
run-name: ${{githun.actions}} is testing the github actions
on: ['push']
jobs:
  firstStage:
    runs-on: ubuntu-latest
    steps:
      - run : echo "haello worls"
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
